### ISSUE TITLE
dashboard admin

### ISSUE THREAD

**Issue by mcsmsxfm56** [MacarenaRodriguez1993/Emme-3D#119]
- [ ] mostrar todos los usuarios con foto de perfil y datos (ya hay una ruta hecha en el backend GET /users)

- [ ] crear, editar, eliminar, filtrar y buscar productos (FILTROS: categoria)(los productos solo tienen una categoria)(debe mostrar stock)(para todo esto tambien hay rutas hechas, los filtros se pueden reutilizar de los que ya estan hechos en /productos)

- [ ] gestionar imagenes de carrusel

- [ ] crear/eliminar categorias

- [x] #132

- [ ] hacer un historial con todas las ordenes (GET /orders)

- [ ] poder convertir un usuario en admin (rutas hechas, users.js)

- [ ] eliminar a un usuario

- [ ] obligar a un usuario a que cambie de contrasena

**Comment by Pau-Marin** [comment]
Estuve viendo este tutorial durante estás vacaciones (inglés), se ve muy completo https://www.youtube.com/watch?v=0cPCMIuDk2I
