### ISSUE TITLE
crear componente opiniones

### ISSUE THREAD

**Issue by MacarenaRodriguez1993** [MacarenaRodriguez1993/Emme-3D#26]
- [ ] renderizar  opiniones ( nombre del usuario y detalle de la opinion)
//**** se habilita solamente cuando estas logueado **// 
- [ ] agregar input para agregar nueva opinion
- [ ] crear boton con estrellitas para dar valoracion
- [ ] crear boton para enviar la opinion

**Comment by Pau-Marin** [comment]
Cambiado a la Week 2
