### ISSUE TITLE
Crear ruta-controlador para el  Detalle

### ISSUE THREAD

**Issue by MacarenaRodriguez1993** [MacarenaRodriguez1993/Emme-3D#27]
- [ ] crear ruta product/details/:id que permita ver los detalles de un producto
(nombre - categoria - precio - stock - descripcion - img )

**Comment by Pau-Marin** [comment]
@121218952415 @mcsmsxfm56 duplicada con #29
Poneos de acuerdo para cerrar una de las 2 (Creo que esta ya que la otra está In Progress)

**Comment by mcsmsxfm56** [comment]
ok ahi cierro esta tarea
