### ISSUE TITLE
crear ruta traer producto por nombre

### ISSUE THREAD

**Issue by MacarenaRodriguez1993** [MacarenaRodriguez1993/Emme-3D#29]
- [x] crear GET/ product?name=''

Obtener los productos que coincidan con el nombre ingresado por query

**Comment by Pau-Marin** [comment]
Se podría adaptar para que fuera cualquier query y no solo nombre, así es más versátil para el front

**Comment by mcsmsxfm56** [comment]
> Se podría adaptar para que fuera cualquier query y no solo nombre, así es más versátil para el front

mi no entender
