### ISSUE TITLE
Crear rutas para Front (Week 2)

### ISSUE THREAD

**Issue by Pau-Marin** [MacarenaRodriguez1993/Emme-3D#65]
Estas son las tareas a realizar para tener todas las rutas.

## Productos:
- [x] #30 Editar producto existente
- [x] #46

## Categorías:
- [x] #48
- [x] #49
- [x] #50

## Ordenes (Pedidos):
- [x] #53
- [x] #51

## Usuarios:
- [x] #55
- [x] #56
- [x] #57
- [x] #58
- [x] #59

**Comment by cflg** [comment]
**Imagenes:**

- [ ] Crear ruta para crear imagenes con nombre y url
- [ ] Crear ruta para borrar imagenes

**Comment by Pau-Marin** [comment]
@cflg He creado #129 para las nuevas, así las de admin (Y si surgen más) también las vamos añadiendo ahí
