### ISSUE TITLE
US #4 T1 Crear formulario controlado

### ISSUE THREAD

**Issue by cflg** [MacarenaRodriguez1993/Emme-3D#9]
Crear el formulario controlado necesario para agregar productos

**Comment by cflg** [comment]
Esta listo para el primer sprint pero no esta terminado.

**Comment by Pau-Marin** [comment]
@cflg Que faltará para acabarlo?

**Comment by Pau-Marin** [comment]
Según comentado falta integración con Cloudinary o simlar, lo daremos por OK para este Sprint y ya de cara al Sprint Week 2 revisamos eso.

Cierro la issue ya que se implementó en #34
